### ISSUE TITLE
Add 'Request a quote' or 'Contact us' button

### ISSUE THREAD

**Issue by nikeshbalami** [okfnepal/idms-page#3]
Currently, the IDMS page doesn't have a space for visitors to find the contact details or ask for a quotation. The aim is to add the button somewhere so that it will be easier for visitors to contact us if they are interested in the project.

### Acceptance Criteria
- [x] I have the button added

### Tasks
- [x] Look into some of the references
- [x] Find a suitable place on the IDMS page and add the button
- [x] Deploy it

**Comment by Zaymes** [comment]
@nikeshbalami design is in figma file, can we go with this?
![image](https://github.com/okfnepal/idms-page/assets/28755348/0f2ace2f-b80a-4d3a-8ec8-117c7adc4472)
![image](https://github.com/okfnepal/idms-page/assets/28755348/525b6424-49f0-4f33-bb79-587cad49e6b8)

**Comment by nikeshbalami** [comment]
@Zaymes I have updated the design in Figma. Some alignment needs to be considered, otherwise, we are good to go.

**Comment by nikeshbalami** [comment]
@Zaymes Contact wala send gareako email chai info@oknp.org ma janee banaum hai.

**Comment by Zaymes** [comment]
@nikeshbalami info@oknp.org ko lagi euta account create grana paryo mail ko lagi. yesma https://formspree.io/

**Comment by nikeshbalami** [comment]
Huss. I have created it.

**Comment by sagargg** [comment]
@Zaymes   Can we add same text next form?  
"Interested in collaborating, seeing a demo, or obtaining answers to your questions?
We're just an email away."

<img width="1512" alt="Screenshot 2024-02-16 at 8 00 11 PM" src="https://github.com/okfnepal/idms-page/assets/87696933/74faed89-4ed8-4d40-911f-76197fc0ff62">

**Comment by Zaymes** [comment]
@sagargg can we make it like this?
![image](https://github.com/okfnepal/idms-page/assets/28755348/4ead11de-f632-4f67-9bc6-8515f83be43d)

**Comment by sagargg** [comment]
@Zaymes  maybe without a border and aligned with the input of the first field, I feel it will look better and fill the blank gap more seamlessly.

**Comment by Zaymes** [comment]
Closing as done
