### ISSUE TITLE
Update the 'About IDMS' page content

### ISSUE THREAD

**Issue by nikeshbalami** [okfnepal/idms-page#5]
Currently, the very basic contact is visible on the About page, we need to update and provide comprehensive information reading the IDMS so that visitors can find all the details on the same page.

### Acceptance Criteria
- [x] I have updated the page with the content

### Tasks
- [x] Develop the content for the page: https://docs.google.com/document/d/1Z7uCRac-Gx16zGJly0JkimhLky-v2qO99YPDCr3tH9s/edit?usp=sharing
- [x] Update the content in the code base
- [x] Implement the change

**Comment by Zaymes** [comment]
Closing as done, updated about page with commit [01e6dac](https://github.com/okfnepal/idms-page/commit/01e6dac35711c0fc734458af65a44dbfd1ed7f66)
